"""Changed the values of the SelfReports table to match DECODE season, added condition that chooses whether or not to display a SelfReport

Revision ID: 17b5165d132e
Revises: 0cb6f834a184
Create Date: 2025-10-15 05:33:41.106341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b5165d132e'
down_revision: Union[str, Sequence[str], None] = '0cb6f834a184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_reports', 'depot_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('self_reports', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('self_reports', sa.Column('season', sa.Integer(), nullable=False))
    op.add_column('self_reports', sa.Column('match_number', sa.Integer(), nullable=False))
    op.add_column('self_reports', sa.Column('event_id', sa.String(), nullable=False))
    op.add_column('self_reports', sa.Column('tournament_level', sa.String(), nullable=False))
    op.add_column('self_reports', sa.Column('classified_amount_auto', sa.Integer(), nullable=False))
    op.add_column('self_reports', sa.Column('overflow_amount_auto', sa.Integer(), nullable=True))
    op.add_column('self_reports', sa.Column('can_collect_from_human_player', sa.Boolean(), nullable=False))
    op.add_column('self_reports', sa.Column('can_deposit_close', sa.Boolean(), nullable=False))
    op.add_column('self_reports', sa.Column('can_deposit_far', sa.Boolean(), nullable=False))
    op.add_column('self_reports', sa.Column('can_leave', sa.Boolean(), nullable=False))
    op.add_column('self_reports', sa.Column('can_motif_in_auto', sa.Boolean(), nullable=False))
    op.add_column('self_reports', sa.Column('classified_amount', sa.Integer(), nullable=False))
    op.add_column('self_reports', sa.Column('depot_amount', sa.Integer(), nullable=False))
    op.alter_column('self_reports', 'additional_info',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('self_reports_creator_id_fkey'), 'self_reports', type_='foreignkey')
    op.create_foreign_key(None, 'self_reports', 'users', ['user_id'], ['_id'])
    op.drop_column('self_reports', 'teleop_scoring_gamepiece_1')
    op.drop_column('self_reports', 'profile_img_url')
    op.drop_column('self_reports', 'auto_scoring_gamepiece_1')
    op.drop_column('self_reports', 'bonus_3')
    op.drop_column('self_reports', 'spikemark_bonus')
    op.drop_column('self_reports', 'can_auto_park')
    op.drop_column('self_reports', 'teleop_scoring_gamepiece_2')
    op.drop_column('self_reports', 'auto_scoring_gamepiece_2')
    op.drop_column('self_reports', 'creator_id')
    op.drop_column('self_reports', 'bonus_2')
    op.drop_column('self_reports', 'bonus_1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_reports', sa.Column('bonus_1', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('self_reports', sa.Column('bonus_2', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('self_reports', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('self_reports', sa.Column('auto_scoring_gamepiece_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('self_reports', sa.Column('teleop_scoring_gamepiece_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('self_reports', sa.Column('can_auto_park', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('self_reports', sa.Column('spikemark_bonus', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('self_reports', sa.Column('bonus_3', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('self_reports', sa.Column('auto_scoring_gamepiece_1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('self_reports', sa.Column('profile_img_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('self_reports', sa.Column('teleop_scoring_gamepiece_1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'self_reports', type_='foreignkey')
    op.create_foreign_key(op.f('self_reports_creator_id_fkey'), 'self_reports', 'users', ['creator_id'], ['_id'])
    op.alter_column('self_reports', 'additional_info',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('self_reports', 'depot_amount')
    op.drop_column('self_reports', 'classified_amount')
    op.drop_column('self_reports', 'can_motif_in_auto')
    op.drop_column('self_reports', 'can_leave')
    op.drop_column('self_reports', 'can_deposit_far')
    op.drop_column('self_reports', 'can_deposit_close')
    op.drop_column('self_reports', 'can_collect_from_human_player')
    op.drop_column('self_reports', 'overflow_amount_auto')
    op.drop_column('self_reports', 'classified_amount_auto')
    op.drop_column('self_reports', 'tournament_level')
    op.drop_column('self_reports', 'event_id')
    op.drop_column('self_reports', 'match_number')
    op.drop_column('self_reports', 'season')
    op.drop_column('self_reports', 'user_id')
    op.alter_column('match_reports', 'depot_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
