"""Condense timing info for CycleInfo

Revision ID: 38778b861199
Revises: a5cf58fbe21e
Create Date: 2026-02-03 17:37:22.300050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38778b861199'
down_revision: Union[str, Sequence[str], None] = 'a5cf58fbe21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_reports_cycle_info', 'time_to_collect',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('match_reports_cycle_info', 'time_to_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_reports_cycle_info', sa.Column('time_to_score', sa.NUMERIC(precision=4, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.alter_column('match_reports_cycle_info', 'time_to_collect',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
