"""Updated Self Report to remove irrelevant rows

Revision ID: 39db6d0b6cbf
Revises: 17b5165d132e
Create Date: 2025-10-15 17:05:02.317639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39db6d0b6cbf'
down_revision: Union[str, Sequence[str], None] = '17b5165d132e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_reports', sa.Column('is_newest', sa.Boolean(), nullable=False))
    op.drop_column('self_reports', 'match_number')
    op.drop_column('self_reports', 'tournament_level')
    op.drop_column('self_reports', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_reports', sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('self_reports', sa.Column('tournament_level', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('self_reports', sa.Column('match_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('self_reports', 'is_newest')
    # ### end Alembic commands ###
