"""auto-events, self_reports, teams

Revision ID: 3e25985d03ac
Revises: 5ee57a79800d
Create Date: 2025-08-18 15:04:36.221435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e25985d03ac'
down_revision: Union[str, Sequence[str], None] = '5ee57a79800d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('liveStreamURL', sa.String(), nullable=True),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('ongoing', sa.Boolean(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('teams',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('number')
    )
    op.create_table('self_reports',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('profile_img_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('auto_scoring_gamepiece_1', sa.Integer(), nullable=False),
    sa.Column('auto_scoring_gamepiece_2', sa.Integer(), nullable=True),
    sa.Column('can_auto_park', sa.Boolean(), nullable=False),
    sa.Column('spikemark_bonus', sa.Boolean(), nullable=True),
    sa.Column('bonus_1', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('bonus_2', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('bonus_3', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('teleop_scoring_gamepiece_1', sa.Integer(), nullable=False),
    sa.Column('teleop_scoring_gamepiece_2', sa.Integer(), nullable=True),
    sa.Column('can_endgame_park', sa.Boolean(), nullable=False),
    sa.Column('ascent_level', sa.Integer(), nullable=False),
    sa.Column('additional_info', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users._id'], ),
    sa.ForeignKeyConstraint(['team_number'], ['teams.number'], ),
    sa.PrimaryKeyConstraint('_id', 'can_auto_park', 'can_endgame_park')
    )
    op.add_column('match_reports', sa.Column('team_number', sa.Integer(), nullable=False))
    op.add_column('match_reports', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('match_reports', sa.Column('event_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('match_reports_users_fk'), 'match_reports', type_='foreignkey')
    op.create_foreign_key(None, 'match_reports', 'events', ['event_id'], ['_id'])
    op.create_foreign_key(None, 'match_reports', 'teams', ['team_number'], ['number'])
    op.create_foreign_key(None, 'match_reports', 'users', ['user_id'], ['_id'])
    op.drop_column('match_reports', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_reports', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'match_reports', type_='foreignkey')
    op.drop_constraint(None, 'match_reports', type_='foreignkey')
    op.drop_constraint(None, 'match_reports', type_='foreignkey')
    op.create_foreign_key(op.f('match_reports_users_fk'), 'match_reports', 'users', ['creator_id'], ['_id'], ondelete='CASCADE')
    op.drop_column('match_reports', 'event_id')
    op.drop_column('match_reports', 'user_id')
    op.drop_column('match_reports', 'team_number')
    op.drop_index(op.f('ix_self_reports__id'), table_name='self_reports')
    op.drop_table('self_reports')
    op.drop_index(op.f('ix_teams__id'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('events')
    # ### end Alembic commands ###
