"""Change timing column name

Revision ID: 422350ea17ee
Revises: 38778b861199
Create Date: 2026-02-03 17:38:35.331399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422350ea17ee'
down_revision: Union[str, Sequence[str], None] = '38778b861199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_reports_cycle_info', sa.Column('cycle_time', sa.Float(), server_default=sa.text('0'), nullable=True))
    op.drop_column('match_reports_cycle_info', 'time_to_collect')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_reports_cycle_info', sa.Column('time_to_collect', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_column('match_reports_cycle_info', 'cycle_time')
    # ### end Alembic commands ###
