"""Change the SelfReport table based on current frontend

Revision ID: 6e4e6084d089
Revises: ad7b4a986750
Create Date: 2025-11-02 08:53:27.011009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4e6084d089'
down_revision: Union[str, Sequence[str], None] = 'ad7b4a986750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_reports', sa.Column('motif_amount_auto', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('self_reports', sa.Column('overflow_amount_teleop', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('self_reports', sa.Column('average_collection_time', sa.Numeric(precision=4, scale=2), server_default=sa.text('0'), nullable=True))
    op.add_column('self_reports', sa.Column('time_to_shoot', sa.Numeric(precision=4, scale=2), server_default=sa.text('0'), nullable=True))
    op.add_column('self_reports', sa.Column('time_to_park', sa.Numeric(precision=4, scale=2), server_default=sa.text('0'), nullable=True))
    op.add_column('self_reports', sa.Column('can_park_two_robots', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.alter_column('self_reports', 'overflow_amount_auto',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('self_reports', 'can_endgame_park')
    op.drop_column('self_reports', 'can_collect_from_human_player')
    op.drop_column('self_reports', 'can_motif_in_auto')
    op.drop_column('self_reports', 'can_leave')
    op.drop_column('self_reports', 'ascent_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_reports', sa.Column('ascent_level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('self_reports', sa.Column('can_leave', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('self_reports', sa.Column('can_motif_in_auto', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('self_reports', sa.Column('can_collect_from_human_player', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('self_reports', sa.Column('can_endgame_park', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('self_reports', 'overflow_amount_auto',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('self_reports', 'can_park_two_robots')
    op.drop_column('self_reports', 'time_to_park')
    op.drop_column('self_reports', 'time_to_shoot')
    op.drop_column('self_reports', 'average_collection_time')
    op.drop_column('self_reports', 'overflow_amount_teleop')
    op.drop_column('self_reports', 'motif_amount_auto')
    # ### end Alembic commands ###
