"""redefined SelfReport to include making reports for teams that don't have the app

Revision ID: 936064bcfea8
Revises: e092cb85b234
Create Date: 2026-01-17 06:15:19.257981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936064bcfea8'
down_revision: Union[str, Sequence[str], None] = 'e092cb85b234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_reports', sa.Column('creator_team_number', sa.Integer(), nullable=False, server_default="130"))
    op.drop_constraint(op.f('self_reports_team_number_fkey'), 'self_reports', type_='foreignkey')
    op.create_foreign_key(None, 'self_reports', 'teams', ['creator_team_number'], ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'self_reports', type_='foreignkey')
    op.create_foreign_key(op.f('self_reports_team_number_fkey'), 'self_reports', 'teams', ['team_number'], ['number'])
    op.drop_column('self_reports', 'creator_team_number')
    # ### end Alembic commands ###
