"""Renamed depot columns to motif due to how useless motifs are.

Revision ID: a193c975593d
Revises: e1bf7857bb14
Create Date: 2025-11-12 21:24:01.881798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a193c975593d'
down_revision: Union[str, Sequence[str], None] = 'e1bf7857bb14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_reports', sa.Column('motif_amount_teleop', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_column('match_reports', 'depot_amount_teleop')
    op.add_column('self_reports', sa.Column('motif_amount_teleop', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_column('self_reports', 'depot_amount_teleop')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_reports', sa.Column('depot_amount_teleop', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('self_reports', 'motif_amount_teleop')
    op.add_column('match_reports', sa.Column('depot_amount_teleop', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('match_reports', 'motif_amount_teleop')
    # ### end Alembic commands ###
