"""Adding CycleInfo table to work with MatchReport

Revision ID: a5cf58fbe21e
Revises: 936064bcfea8
Create Date: 2026-01-17 09:33:47.979940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5cf58fbe21e'
down_revision: Union[str, Sequence[str], None] = '936064bcfea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_reports_cycle_info',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('match_report_id', sa.Integer(), nullable=False),
    sa.Column('time_to_collect', sa.Numeric(precision=4, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('collection_position', sa.String(), nullable=False),
    sa.Column('time_to_score', sa.Numeric(precision=4, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('scoring_position', sa.String(), nullable=False),
    sa.Column('artifacts_collected', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('artifacts_scored', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['match_report_id'], ['match_reports._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.add_column('match_reports', sa.Column('far_zone_collection_freq', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('match_reports', sa.Column('classifier_collection_freq', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('match_reports', sa.Column('human_player_collection_freq', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('match_reports', sa.Column('close_zone_scoring_freq', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('match_reports', sa.Column('far_zone_scoring_freq', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_reports', 'far_zone_scoring_freq')
    op.drop_column('match_reports', 'close_zone_scoring_freq')
    op.drop_column('match_reports', 'human_player_collection_freq')
    op.drop_column('match_reports', 'classifier_collection_freq')
    op.drop_column('match_reports', 'far_zone_collection_freq')
    op.drop_table('match_reports_cycle_info')
    # ### end Alembic commands ###
