"""Added rookie year and organization to Teams table

Revision ID: ad7b4a986750
Revises: 39db6d0b6cbf
Create Date: 2025-10-17 20:45:26.777358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7b4a986750'
down_revision: Union[str, Sequence[str], None] = '39db6d0b6cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('organization', sa.String(), nullable=False, server_default="None"))
    op.add_column('teams', sa.Column('rookie_year', sa.Integer(), nullable=False, server_default="2007"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'rookie_year')
    op.drop_column('teams', 'organization')
    # ### end Alembic commands ###
