"""empty message

Revision ID: d82ebe578b06
Revises: f846d14e7373
Create Date: 2025-11-03 17:52:12.800544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82ebe578b06'
down_revision: Union[str, Sequence[str], None] = 'f846d14e7373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_reports', sa.Column('creator_team_number', sa.Integer(), nullable=False))
    op.add_column('match_reports', sa.Column('motif_amount_auto', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('match_reports', sa.Column('classified_amount_teleop', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('match_reports', sa.Column('depot_amount_teleop', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('match_reports', sa.Column('overflow_amount_teleop', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('match_reports', sa.Column('shots_made_teleop', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('match_reports', sa.Column('shots_attempted_teleop', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.alter_column('match_reports', 'overflow_amount_auto',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('match_reports_team_number_fkey'), 'match_reports', type_='foreignkey')
    op.create_foreign_key(None, 'match_reports', 'teams', ['creator_team_number'], ['number'])
    op.drop_column('match_reports', 'can_motif_in_auto')
    op.drop_column('match_reports', 'can_collect_from_human_player')
    op.drop_column('match_reports', 'can_deposit_close')
    op.drop_column('match_reports', 'can_leave')
    op.drop_column('match_reports', 'can_deposit_far')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_reports', sa.Column('can_deposit_far', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('match_reports', sa.Column('can_leave', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('match_reports', sa.Column('can_deposit_close', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('match_reports', sa.Column('can_collect_from_human_player', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('match_reports', sa.Column('can_motif_in_auto', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'match_reports', type_='foreignkey')
    op.create_foreign_key(op.f('match_reports_team_number_fkey'), 'match_reports', 'teams', ['team_number'], ['number'])
    op.alter_column('match_reports', 'overflow_amount_auto',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('match_reports', 'shots_attempted_teleop')
    op.drop_column('match_reports', 'shots_made_teleop')
    op.drop_column('match_reports', 'overflow_amount_teleop')
    op.drop_column('match_reports', 'depot_amount_teleop')
    op.drop_column('match_reports', 'classified_amount_teleop')
    op.drop_column('match_reports', 'motif_amount_auto')
    op.drop_column('match_reports', 'creator_team_number')
    # ### end Alembic commands ###
