"""updated MatchReport to match new UI

Revision ID: dd80b6888b11
Revises: a193c975593d
Create Date: 2026-01-16 23:17:59.641858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd80b6888b11'
down_revision: Union[str, Sequence[str], None] = 'a193c975593d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('self_reports', 'can_deposit_far')
    op.drop_column('self_reports', 'average_collection_time')
    op.drop_column('self_reports', 'can_deposit_close')
    op.drop_column('self_reports', 'time_to_shoot')
    op.drop_column('self_reports', 'time_to_park')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_reports', sa.Column('time_to_park', sa.NUMERIC(precision=4, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('self_reports', sa.Column('time_to_shoot', sa.NUMERIC(precision=4, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('self_reports', sa.Column('can_deposit_close', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('self_reports', sa.Column('average_collection_time', sa.NUMERIC(precision=4, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('self_reports', sa.Column('can_deposit_far', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
