"""empty message

Revision ID: ddfe23e0df2e
Revises: 3e25985d03ac
Create Date: 2025-09-05 16:52:19.734564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfe23e0df2e'
down_revision: Union[str, Sequence[str], None] = '3e25985d03ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE events CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users__id'), 'users', ['_id'], unique=False)
    op.create_foreign_key(op.f('match_reports_event_id_fkey'), 'match_reports', 'events', ['event_id'], ['_id'])
    op.alter_column('match_reports', 'event_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_table('events',
    sa.Column('_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('season', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('liveStreamURL', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('started', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ongoing', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('finished', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('_id', name=op.f('events_pkey'))
    )
    # ### end Alembic commands ###
