"""updated SelfReport to match new UI (part 2)

Revision ID: e092cb85b234
Revises: dd80b6888b11
Create Date: 2026-01-16 23:23:11.401095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e092cb85b234'
down_revision: Union[str, Sequence[str], None] = 'dd80b6888b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_reports', sa.Column('starting_position', sa.String(), nullable=False, server_default="Close Zone"))
    op.add_column('self_reports', sa.Column('collection_position', sa.String(), nullable=False, server_default="Classifier"))
    op.add_column('self_reports', sa.Column('scoring_position', sa.String(), nullable=False, server_default="Close Zone"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('self_reports', 'scoring_position')
    op.drop_column('self_reports', 'collection_position')
    op.drop_column('self_reports', 'starting_position')
    # ### end Alembic commands ###
