"""Added auto columns for matchreport

Revision ID: e1bf7857bb14
Revises: d82ebe578b06
Create Date: 2025-11-12 21:01:31.717383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bf7857bb14'
down_revision: Union[str, Sequence[str], None] = 'd82ebe578b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_reports', sa.Column('shots_made_auto', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('match_reports', sa.Column('shots_attempted_auto', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_column('match_reports', 'classified_amount')
    op.drop_column('match_reports', 'can_endgame_park')
    op.drop_column('match_reports', 'ascent_level')
    op.drop_column('match_reports', 'depot_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_reports', sa.Column('depot_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('match_reports', sa.Column('ascent_level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('match_reports', sa.Column('can_endgame_park', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('match_reports', sa.Column('classified_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('match_reports', 'shots_attempted_auto')
    op.drop_column('match_reports', 'shots_made_auto')
    # ### end Alembic commands ###
