"""Fixing mistake in teleop column naming convention in SelfReport

Revision ID: f846d14e7373
Revises: 6e4e6084d089
Create Date: 2025-11-02 09:01:03.267347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f846d14e7373'
down_revision: Union[str, Sequence[str], None] = '6e4e6084d089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_reports', sa.Column('classified_amount_teleop', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('self_reports', sa.Column('depot_amount_teleop', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_column('self_reports', 'depot_amount')
    op.drop_column('self_reports', 'classified_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_reports', sa.Column('classified_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('self_reports', sa.Column('depot_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('self_reports', 'depot_amount_teleop')
    op.drop_column('self_reports', 'classified_amount_teleop')
    # ### end Alembic commands ###
