"""Updated match report table based on new DECODE season

Revision ID: 0cb6f834a184
Revises: 640508c3c244
Create Date: 2025-09-13 17:35:11.602152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb6f834a184'
down_revision: Union[str, Sequence[str], None] = '640508c3c244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_reports', sa.Column('classified_amount_auto', sa.Integer(), nullable=False))
    op.add_column('match_reports', sa.Column('overflow_amount_auto', sa.Integer(), nullable=True))
    op.add_column('match_reports', sa.Column('can_collect_from_human_player', sa.Boolean(), nullable=False))
    op.add_column('match_reports', sa.Column('can_deposit_close', sa.Boolean(), nullable=False))
    op.add_column('match_reports', sa.Column('can_deposit_far', sa.Boolean(), nullable=False))
    op.add_column('match_reports', sa.Column('can_leave', sa.Boolean(), nullable=False))
    op.add_column('match_reports', sa.Column('can_motif_in_auto', sa.Boolean(), nullable=False))
    op.add_column('match_reports', sa.Column('classified_amount', sa.Integer(), nullable=False))
    op.add_column('match_reports', sa.Column('depot_amount', sa.Integer(), nullable=True))
    op.drop_column('match_reports', 'bonus_3')
    op.drop_column('match_reports', 'teleop_scoring_gamepiece_2')
    op.drop_column('match_reports', 'spikemark_bonus')
    op.drop_column('match_reports', 'auto_scoring_gamepiece_1')
    op.drop_column('match_reports', 'bonus_1')
    op.drop_column('match_reports', 'bonus_2')
    op.drop_column('match_reports', 'teleop_scoring_gamepiece_1')
    op.drop_column('match_reports', 'auto_scoring_gamepiece_2')
    op.drop_column('match_reports', 'can_auto_park')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_reports', sa.Column('can_auto_park', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('match_reports', sa.Column('auto_scoring_gamepiece_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match_reports', sa.Column('teleop_scoring_gamepiece_1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('match_reports', sa.Column('bonus_2', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('match_reports', sa.Column('bonus_1', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('match_reports', sa.Column('auto_scoring_gamepiece_1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('match_reports', sa.Column('spikemark_bonus', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('match_reports', sa.Column('teleop_scoring_gamepiece_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match_reports', sa.Column('bonus_3', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('match_reports', 'depot_amount')
    op.drop_column('match_reports', 'classified_amount')
    op.drop_column('match_reports', 'can_motif_in_auto')
    op.drop_column('match_reports', 'can_leave')
    op.drop_column('match_reports', 'can_deposit_far')
    op.drop_column('match_reports', 'can_deposit_close')
    op.drop_column('match_reports', 'can_collect_from_human_player')
    op.drop_column('match_reports', 'overflow_amount_auto')
    op.drop_column('match_reports', 'classified_amount_auto')
    # ### end Alembic commands ###
